### ISSUE TITLE
Form field vaildation resulting in post request error instead giving feedback to user

### ISSUE THREAD

**Issue by annakrystalli** [reprohack/reprohack_site#205]
This was noted with a paper submission which was generating the following error.
![image](https://user-images.githubusercontent.com/5583057/153009579-37ce2a10-343c-4ae1-a58d-2a06070d012f.png)

The problem was a malformed `data-url` field which contained a space.

The expected behaviour would be to return a validation warning and ideally direct the user to the malformed field instead of throwing a request error. Oddly, if the **Submit** button is right clicked so the result opens in a new tab, it DOES have the expected behaviour! 🤷‍♀️

![image](https://user-images.githubusercontent.com/5583057/153007866-36a5a529-f5b5-46c4-a6ed-8c049d8a9f8b.png)

**Comment by annakrystalli** [comment]
Full Traceback:

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/paper/62/edit/

Django Version: 3.1.4
Python Version: 3.8.10
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.forms',
 'crispy_forms',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'datetimewidget',
 'django_toggle_switch_widget',
 'taggit',
 'markdownx',
 'django_countries',
 'gmailapi_backend',
 'reprohack_hub.apps.ReprohackConfig',
 'compressor',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.common.BrokenLinkEmailsMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/templates/bootstrap4/field.html, error at line 42
   'str' object has no attribute 'name'
   32 :                     {% crispy_field field 'class' 'form-check-input' %}
   33 :                 {% endif %}
   34 :                 <label for="{{ field.id_for_label }}" class="{%if use_custom_control%}custom-control-label{% else %}form-check-label{% endif %}{% if field.field.required %} requiredField{% endif %}">
   35 :                     {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
   36 :                 </label>
   37 :                 {% include 'bootstrap4/layout/help_text_and_errors.html' %}
   38 :             {% elif field|is_file and use_custom_control  %}
   39 :                 {% include 'bootstrap4/layout/field_file.html' %}
   40 :             {% else %}
   41 :                 <div class="{{ field_class }}">
   42 :                      {% crispy_field field %} 
   43 :                     {% include 'bootstrap4/layout/help_text_and_errors.html' %}
   44 :                 </div>
   45 :             {% endif %}
   46 :         {% endif %}
   47 :     </{% if tag %}{{ tag }}{% else %}div{% endif %}>
   48 :     {% if field|is_checkbox %}
   49 :         {% if label_class %}
   50 :             </div>
   51 :         {% endif %}
   52 :         </div>


Traceback (most recent call last):
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 203, in render
    c = self.get_render(context).flatten()
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 119, in get_render
    actual_form.form_html = helper.render_layout(
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/helper.py", line 301, in render_layout
    html = self.layout.render(form, self.form_style, context, template_pack=template_pack)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/layout.py", line 135, in render
    return self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/layout.py", line 96, in get_rendered_fields
    return "".join(
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/layout.py", line 97, in <genexpr>
    render_field(field, form, form_style, context, template_pack=template_pack, **kwargs)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/utils.py", line 66, in render_field
    return field.render(form, form_style, context, template_pack=template_pack,)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/layout.py", line 457, in render
    return self.get_rendered_fields(
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/layout.py", line 96, in get_rendered_fields
    return "".join(
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/layout.py", line 97, in <genexpr>
    render_field(field, form, form_style, context, template_pack=template_pack, **kwargs)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/utils.py", line 139, in render_field
    html = template.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/crispy_forms/templatetags/crispy_forms_field.py", line 155, in render
    return str(field)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/forms/boundfield.py", line 93, in as_widget
    return widget.render(
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/Users/Anna/miniconda3/envs/reprohack/lib/python3.8/site-packages/django/forms/widgets.py", line 233, in get_context
    'value': self.format_value(value),
  File "/Users/Anna/Documents/workflows/Reprohack-org/reprohack_site/reprohack_hub/forms.py", line 91, in format_value
    return ",".join([tag.name for tag in value])
  File "/Users/Anna/Documents/workflows/Reprohack-org/reprohack_site/reprohack_hub/forms.py", line 91, in <listcomp>
    return ",".join([tag.name for tag in value])

Exception Type: AttributeError at /paper/62/edit/
Exception Value: 'str' object has no attribute 'name'
```

**Comment by twinkarma** [comment]
Here's the fix

```
class TagWidget(Widget):
    template_name = "paper/tag_input.html"

    def format_value(self, value):
        """
        Convert taggit's tag manger objects to plain comma separated text
        :param value:
        :return:
        """

        if value is list:
            return ",".join([tag.name in value])
        elif value:
            return value
        else:
            return ""


```

**Comment by twinkarma** [comment]
In the validation loop the tag widget is reformatting an already formatted value so the previous code broke as it was looking for an array of tags and not a single string value
