### ISSUE TITLE
Missing assets for Owl Carousel 2

### ISSUE THREAD

**Issue by willfurnass** [reprohack/reprohack_site#41]
On the `dev` branch Django throws an error due to it being unable to post-process `reprohack/css/owl.carousel.min.css`.  This is because the referenced asset `reprohack/css/owl.video.play.png` couldn't be found:

```
django_1        | Post-processing 'reprohack/css/owl.carousel.min.css' failed!
django_1        | 
django_1        | Traceback (most recent call last):
django_1        |   File "/app/manage.py", line 31, in <module>
django_1        |     execute_from_command_line(sys.argv)
django_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
django_1        |     utility.execute()
django_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
django_1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
django_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
django_1        |     self.execute(*args, **cmd_options)
django_1        |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
django_1        |     output = self.handle(*args, **options)
django_1        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
django_1        |     collected = self.collect()
django_1        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 133, in collect
django_1        |     raise processed
django_1        | whitenoise.storage.MissingFileError: The file 'reprohack/css/owl.video.play.png' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f13a9c48d90>.
django_1        | 
django_1        | The CSS file 'reprohack/css/owl.carousel.min.css' references a file which could not be found:
django_1        |   reprohack/css/owl.video.play.png
django_1        | 
django_1        | Please check the URL references in this CSS file, particularly any
django_1        | relative paths which might be pointing to the wrong location.
```

Should that `.png` be vendored into this repo?  It's present in the distribution for the latest Owl Carousel available from the Owl Carousel website. 

Alternatively, should the Owl Carousel dependency be managed using `npm` instead?  Any comments @spool?

**Comment by griff-rees** [comment]
Yeah ideally Owl is managed by `npm`. I was trying to fix this back in August and when last I checked it's no longer maintained: https://www.npmjs.com/package/owl.carousel (last update 2018). The suggestion on that repo https://github.com/OwlCarousel2/OwlCarousel2 is to use this https://github.com/ganlanyuan/tiny-slider. It was hardwired into the reprohack template I'm trying to combine with the one I generated from `django-cookiecutter`. I think I actually mentioned this in one of our meetings. It shouldn't prevent the page from rendering (at least it doesn't with `local.yml`) but it's annoying to fix/replace. Might just comment it out for the sake of rough deployment and come back to it.

**Comment by griff-rees** [comment]
I'm leaning towards altering this or creating a new ticket for managing 'javascript' dependencies. At present we have further issues with other libraries, none of which are managed by `npm` in `package.json` at present. List as far as I know:

```
<script src="{% static 'reprohack/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static 'reprohack/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'reprohack/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'reprohack/js/ajax-form.js' %}"></script>
<script src="{% static 'reprohack/js/waypoints.min.js' %}"></script>
<script src="{% static 'reprohack/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'reprohack/js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'reprohack/js/scrollIt.js' %}"></script>
<script src="{% static 'reprohack/js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'reprohack/js/wow.min.js' %}"></script>
<script src="{% static 'reprohack/js/nice-select.min.js' %}"></script>
<script src="{% static 'reprohack/js/jquery.slicknav.min.js' %}"></script>
<script src="{% static 'reprohack/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'reprohack/js/plugins.js' %}"></script>
<script src="{% static 'reprohack/js/gijgo.min.js' %}"></script>
<script src="{% static 'reprohack/leaflet/leaflet.awesome-markers.js' %}"></script>
```

similar deal for css:
```
<link rel='stylesheet' href="{% static 'reprohack/css/owl.carousel.min.css'%}">
<link rel='stylesheet' href="{% static 'reprohack/css/magnific-popup.css'%}">
<link rel='stylesheet' href="{% static 'reprohack/css/font-awesome.min.css'%}">
<link rel="stylesheet" href="{% static 'reprohack/leaflet/leaflet.awesome-markers.css' %}%">
<link rel='stylesheet' href="{% static 'reprohack/css/themify-icons.css'%}">
<link rel='stylesheet' href="{% static 'reprohack/css/nice-select.css'%}">
<link rel='stylesheet' href="{% static 'reprohack/css/flaticon.css'%}">
<link rel='stylesheet' href="{% static 'reprohack/css/gijgo.css'%}">
<link rel='stylesheet' href="{% static 'reprohack/css/animate.css'%}">
<link rel='stylesheet' href="{% static 'reprohack/css/slicknav.css'%}">
```

So maybe what this should be is a general question of *what do we need to get a basic test deploy finally up on `dev`* and I'll create a proper ticket on implementation decisions as to whether we go for [`CDN`](https://developer.mozilla.org/en-US/docs/Glossary/CDN) where possible and `npm` elsewhere. Sorry, quite tired, hope that's enough to get the conversation going on Tuesday.

**Comment by annakrystalli** [comment]
Vendor missing assets now for simplicity

**Comment by annakrystalli** [comment]
Can we close this issue now?

**Comment by willfurnass** [comment]
@annakrystalli has it been rectified by a PR yet?

**Comment by annakrystalli** [comment]
Ah good point! Not sure. @griff-rees feel free to close when it has. PS make sure you sign up so it counts towards your Hacktoberfest tally! 😜

**Comment by griff-rees** [comment]
I'm closing this, but I think I'm going to set up a new general one. Will refer to this in #45.
